export { default as Header } from './Header'
export { default as CanvasParticles } from './CanvasParticles'
export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Skills } from './Skills'
export { default as Projects } from './Projects'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
export { default as BlurText } from './BlurText'
export { default as PrimaryButton } from './PrimaryButton'

